$(var controller_prefix)controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    hande_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_hande_controller:
      type: position_controllers/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

#$(var controller_prefix)hande_joint_state_broadcaster:
#  ros__parameters:
#    joints:
#      - arm_0_finger_1_joint
#    interfaces:
#      - position
#      - velocity

$(var controller_prefix)robotiq_gripper_hande_controller:
  ros__parameters:
    default: true
    joint: arm_0_finger_1_joint

$(var controller_prefix)robotiq_activation_controller:
  ros__parameters:
    default: true
