# Full set of configurations
#- ros_topic_name: "/cmd_vel"
#  ros_type_name: "geometry_msgs/msg/Twist"
#  gz_type_name: "ignition::msgs::Twist"
#  subscriber_queue: 10       # Default 10
#  publisher_queue: 10        # Default 10
#  lazy: false                # Default "false"
#  direction: GZ_TO_ROS  # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Gz topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gz

# this is used by the telop panel in Gazebo
- ros_topic_name: "cmd_vel_unstamped"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: GZ_TO_ROS